from typing import TypedDict, List, Optional, Literal

class Job(TypedDict):
    title: str
    link: str
    salary_range: str
    description: str
    company_name: str
    pain_points: List[str]           # extracted by LLM step 1
    pitch: str                       # generated by LLM step 2
    user_feedback: str               # your last Telegram message
    modification_rounds: int         # how many times you asked to modify
    status: Literal["pending", "approved", "rejected", "applied", "error"]
    error_message: Optional[str]

class GraphState(TypedDict):
    jobs: List[Job]
    current_job_index: int
    run_id: str                      # timestamp of this run
    errors: List[str]                # global errors
    telegram_chat_id: str
